#msg: Could not import python modules: pycurl. Please install python-pycurl package.
- name: Install python-software-properties
  action: apt pkg=python-software-properties state=present

- name: Install python-pycurl
  apt: pkg={{ item }} state=installed
  with_items:
   - python-pycurl

- name: Add nginx ppa
  action: apt_repository repo=ppa:nginx/stable state=present

- name: Install nginx
  action: apt pkg=nginx state=installed
  notify:
    - restart nginx

- name: Set nginx main config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx
