- name: Add nodejs apt repository
  apt_repository: repo=ppa:chris-lea/node.js state=present

- name: Install nodejs
  action: apt pkg={{ item }} state=installed force=yes
  with_items:
    - nodejs

- name: Install nodejs packages
  npm: name={{ item }} global=yes state=present
  with_items: nodejs_packages