# php5-common php-apc php5-gd php5-dev php5-curl php5-cli php5-mysql php5-intl php-pear php5-imap php5-mcrypt php5-ps php5-pspell php5-recode php5-sqlite php5-tidy php5-xmlrpc php5-xsl php5-json
# php5-xdebug

- name: Install php packages
  action: apt pkg={{ item }} state=installed
  with_items:
    - php-pear
    - php-apc
    - php5-fpm
    - php5-cli
    - php5-dev
    - php5-gd
    - php5-curl
    - php5-mcrypt
    # - php5-xdebug
    - php5-sqlite
    - php5-mysql
    - php5-memcache
    - php5-intl
    - php5-tidy
    - php5-imap
    - php5-imagick
    - php5-json

- name: Set cli php.ini
  template: src=php-cli.ini dest=/etc/php5/cli/php.ini
  notify:
    - restart php-fpm

- name: Set php-fpm php.ini
  template: src=php-fpm.ini dest=/etc/php5/fpm/php.ini
  notify:
    - restart php-fpm

- name: Set php-fpm configuration
  template: src=php-fpm.conf dest=/etc/php5/fpm/php-fpm.conf
  notify:
    - restart php-fpm