---
- name: Update apt
  command: /usr/bin/apt-get update

- name: Install common packages
  action: apt pkg={{ item }} state=installed force=yes
  with_items:
    - htop
    - git
    - vim
    - build-essential
    - libpq-dev
    - libxml2-dev
    - libjpeg62
    - libjpeg62-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - imagemagick
    - curl
    - software-properties-common
    - python-dev
    - python-setuptools
    - python-mysqldb
    - python-pycurl
    - unattended-upgrades
    - ruby-dev